name: tarot_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  supabase_flutter: ^2.10.2
  
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

    #dashboard_page
    - assets/images/dashboard_page/the_appointments.png
    - assets/images/dashboard_page/the_packages.png
    - assets/images/dashboard_page/the_reader.png
    - assets/images/dashboard_page/the_testimonies.png
    - assets/images/dashboard_page/settings.png

    #reader_page
    - assets/images/reader_page/the_reader_face.png
    - assets/images/reader_page/reader_art.png

    #packages_page
    - assets/images/packages_page/crown_package.png
    - assets/images/packages_page/coronet_package.png
    - assets/images/packages_page/tiara_package.png
    - assets/images/packages_page/tiara_asset.png
    - assets/images/packages_page/coronet_asset.png
    - assets/images/packages_page/crown_asset.png

    #testimonies_page
    - assets/images/testimonies_page/banner.jpeg
    - assets/images/testimonies_page/user1_ava.png
    - assets/images/testimonies_page/user2_sammy.png
    - assets/images/testimonies_page/user3_summer.png
    - assets/images/testimonies_page/user4_aaron.png
    - assets/images/testimonies_page/user5_shawn.png

    #settings_page
    - assets/images/settings_page/settings.png
    - assets/images/settings_page/edit_button.png
    - assets/images/settings_page/ryan_gosling.jpg

  fonts:
    - family: LuxScript
      fonts:
        - asset: assets/fonts/LuxScript.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: LuxuriousScript
      fonts:
        - asset: assets/fonts/LuxuriousScript-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf